# ???????8080??????
server.port=8080
# ??????????????127.0.0.1????????????
server.address=0.0.0.0

# ??????????????
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ????????????????????
spring.web.resources.static-locations=classpath:/static/